name: Execução de Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  u-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2

      - name: Run tests
        run: cd testandoactions/

      - name: tests
        run: python manage.py test
    
